sudo: required
language: python
addons:
  firefox: latest-nightly

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
  - 'bootstrap/bootstrap.sh'
  - 'pipenv install'

install:
  - pip install tox

jobs:
  include:
    - stage: lint
      python: 3.7
      before_install: skip
      script: tox -e flake8
    - stage: test
      python: 3.7
      script: tox -e py37
