sudo: required
language: python
addons:
  firefox: latest-nightly

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
  - wget https://github.com/tesseract-ocr/tesseract/archive/4.0.0.tar.gz

install:
  - pip install tox

jobs:
  include:
    - stage:
      python: 3.7
      before_install: skip
      script: tox -e flake8
