sudo: required
language: python
addons:
  firefox: latest-nightly

cache:
  directories:
    - $HOME/.cache/pip
    - node_modules

before_install:
  - 'iris/bootstrap/bootstrap.sh'
  - 'pipenv install'

install:
  - pip install tox

before_script:
    - "export DISPLAY=:99.0"
    - "Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &"

jobs:
  include:
    - stage: lint
      python: 3.7
      before_install: skip
      script: tox -e flake8
    - stage: test
      python: 3.7
      script: tox -e py37
